// css units
module.exports = {
  rem: 'rem',
  em: 'em',
  vw: 'vw',
  vh: 'vh',
  px: 'px',
  pct: '%',
  solid: 'solid',
  bold: 'bold',
  center: 'center',
  left: 'left',
  right: 'right',
  absolute: 'absolute',
  pointer: 'pointer',
  none: 'none',
  normal: 'normal',
  flex: 'flex',
  flexEnd: 'flex-end',
  spaceAround: 'space-around',
  spaceBetween: 'space-between',
  row_wrap: 'row wrap',
  row: 'row',
  wrap: 'wrap',
  hidden: 'hidden',
  scroll: 'scroll',
};
